name: Deploy Bicep

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: |
          echo "Installing Bicep CLI..."
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep

      - name: Verify Bicep Installation
        run: |
          echo "Verifying Bicep installation..."
          bicep --version

      - name: List Files in Repository
        run: |
          echo "Listing files in repository..."
          ls -R

      - name: Debug Azure CLI
        run: |
          echo "Azure CLI version:"
          az --version
          echo "Listing available subscriptions:"
          az account list --output table

      - name: Check Environment Variables
        run: |
          echo "Checking environment variables..."
          printenv

      - name: Deploy Bicep templates
        run: |
          echo "Deploying Bicep templates..."
          az deployment sub create --location eastus --template-file src/bicep/mlz.bicep --parameters deployIdentity=Yes firewallSkuTier=Basic resourcePrefix=jgmlz --verbose ingestionAccessMode=Open --verbose
        env:
          AZURE_HTTP_USER_AGENT: "GITHUB_ACTIONS"
